[workspace]
channels = ["conda-forge"]
name = "conv_parametrization"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
numpy = ">=2.4.0,<3"
xarray = ">=2025.12.0,<2026"
ipdb = ">=0.13.13,<0.14"
matplotlib = ">=3.10.8,<4"
scipy = ">=1.16.3,<2"
gsw = ">=3.6.20,<4"
